### ISSUE TITLE
fråga: pågår utveckling i detta projekt?

### ISSUE THREAD

**Issue by spamatica** [solidfox/fribok#1]
Hej,

Ramlade över fribok här om dan och då öppna/fria bokföringsprogram verkligen inte växer på träd blev jag intresserad.

Ser inte att denna har några ändringar från den på sourceforge, förutom att den nyligen är överförd till github. 
Bara ett experiment eller nåt man möjligen kan bygga vidare på?

Jag vet inte om den på sourceforge lever men ser inte ut så...

**Comment by solidfox** [comment]
Detta är bara en koppling mellan sourceforge och GitHub. Vill minnas att jag använde någon svn integration i Git så historik skulle kunna bevaras och ev utveckling på sourceforge skulle kunna integreras lättare. Kanske även åt andra hållet. Hade en tanke om att sätta någon AI agent på att skriva om det men haft för lite tid ens att göra det.

Så det är bara en orörd git-version av fribok.

**Comment by spamatica** [comment]
Tackar för svaret. 
Ska meka lite med det, stör mig över en del väldigt enkla grejer (dialoger som man måste klicka med musen etc) som jag kanske kan fixa till. 
Blir det ett patch-set så får jag väl kolla om det finns någon mottagare på sourceforge sidan :^)

**Comment by kalvdans** [comment]
Fixar mottages på https://gitlab.com/leaflong/fribok-dirty/ :)

**Comment by spamatica** [comment]
okej, roligt att höra! Får väl se om jag nångång får fart på någon egen utveckling ;)
Tvärkollade och ser att jag hade gjort några incheckningar i en fork innan det svalnade... Minns inte i vilken state det var men ser rätt trivialt ut.
https://github.com/spamatica/fribok/commits/verifications_QoL_fixes

Edit: I teorin skulle jag väldigt gärna fortsätta på detta, Fribok är den mest kompetenta bokföringen jag själv hittat som verkligen är fri att att använda. 
Men jag är ingen större javaprogrammerare och får klia mig i huvudet en hel del bara för att få ordning på byggsystemet..
